BEGIN TRANSACTION;
CREATE TABLE apn (
	apn VARCHAR(50) NOT NULL,
	apn_ambr_dl INTEGER NOT NULL,
	apn_ambr_ul INTEGER NOT NULL,
	apn_id INTEGER NOT NULL,
	arp_preemption_capability BOOLEAN,
	arp_preemption_vulnerability BOOLEAN,
	arp_priority INTEGER,
	charging_characteristics VARCHAR(4),
	charging_rule_list VARCHAR(18),
	ip_version INTEGER,
	last_modified VARCHAR(100),
	nbiot BOOLEAN,
	nidd_mechanism INTEGER,
	nidd_preferred_data_mode INTEGER,
	nidd_rds INTEGER,
	nidd_scef_id VARCHAR(512),
	nidd_scef_realm VARCHAR(512),
	pgw_address VARCHAR(50),
	qci INTEGER,
	sgw_address VARCHAR(50),
	PRIMARY KEY (apn_id)
);
CREATE TABLE auc (
	adm1 VARCHAR(20),
	algo VARCHAR(20),
	amf VARCHAR(4) NOT NULL,
	auc_id INTEGER NOT NULL,
	batch_name VARCHAR(20),
	des VARCHAR(128),
	esim BOOLEAN,
	iccid VARCHAR(20),
	imsi VARCHAR(18),
	ki VARCHAR(32) NOT NULL,
	kid VARCHAR(20),
	last_modified VARCHAR(100),
	lpa VARCHAR(128),
	misc1 VARCHAR(128),
	misc2 VARCHAR(128),
	misc3 VARCHAR(128),
	misc4 VARCHAR(128),
	opc VARCHAR(32) NOT NULL,
	pin1 VARCHAR(20),
	pin2 VARCHAR(20),
	psk VARCHAR(128),
	puk1 VARCHAR(20),
	puk2 VARCHAR(20),
	sim_vendor VARCHAR(20),
	sqn BIGINT,
	PRIMARY KEY (auc_id),
	UNIQUE (iccid),
	UNIQUE (imsi)
);
CREATE TABLE charging_rule (
	arp_preemption_capability BOOLEAN,
	arp_preemption_vulnerability BOOLEAN,
	arp_priority INTEGER,
	charging_rule_id INTEGER NOT NULL,
	gbr_dl INTEGER NOT NULL,
	gbr_ul INTEGER NOT NULL,
	last_modified VARCHAR(100),
	mbr_dl INTEGER NOT NULL,
	mbr_ul INTEGER NOT NULL,
	precedence INTEGER,
	qci INTEGER,
	rating_group INTEGER,
	rule_name VARCHAR(20),
	tft_group_id INTEGER,
	PRIMARY KEY (charging_rule_id)
);
CREATE TABLE database_schema_version (
	comment VARCHAR(512),
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
	upgrade_id INTEGER NOT NULL,
	PRIMARY KEY (upgrade_id)
);
CREATE TABLE eir (
	eir_id INTEGER NOT NULL,
	imei VARCHAR(60),
	imsi VARCHAR(60),
	last_modified VARCHAR(100),
	match_response_code INTEGER,
	regex_mode INTEGER,
	PRIMARY KEY (eir_id)
);
CREATE TABLE eir_history (
	imsi_imei VARCHAR(60),
	imsi_imei_history_id INTEGER NOT NULL,
	imsi_imei_timestamp DATETIME,
	last_modified VARCHAR(100),
	match_response_code INTEGER,
	PRIMARY KEY (imsi_imei_history_id),
	UNIQUE (imsi_imei)
);
CREATE TABLE emergency_subscriber (
	access_network_charging_address VARCHAR(512),
	access_network_gateway_address VARCHAR(512),
	emergency_subscriber_id INTEGER NOT NULL,
	gx_origin_host VARCHAR(512),
	gx_origin_realm VARCHAR(512),
	imsi VARCHAR(18),
	ip VARCHAR(512),
	last_modified VARCHAR(100),
	rat_type VARCHAR(512),
	serving_pcscf VARCHAR(512),
	serving_pcscf_timestamp VARCHAR(512),
	serving_pgw VARCHAR(512),
	serving_pgw_timestamp VARCHAR(512),
	PRIMARY KEY (emergency_subscriber_id)
);
CREATE TABLE ims_subscriber (
	ifc_path VARCHAR(512),
	ims_subscriber_id INTEGER NOT NULL,
	imsi VARCHAR(18),
	last_modified VARCHAR(100),
	msisdn VARCHAR(18),
	msisdn_list VARCHAR(1200),
	pcscf VARCHAR(512),
	pcscf_active_session VARCHAR(512),
	pcscf_peer VARCHAR(512),
	pcscf_realm VARCHAR(512),
	pcscf_timestamp DATETIME,
	scscf VARCHAR(512),
	scscf_peer VARCHAR(512),
	scscf_realm VARCHAR(512),
	scscf_timestamp DATETIME,
	sh_profile TEXT,
	sh_template_path VARCHAR(512),
	xcap_profile TEXT,
	PRIMARY KEY (ims_subscriber_id),
	UNIQUE (msisdn)
);
CREATE TABLE operation_log (
	apn_id INTEGER,
	auc_id INTEGER,
	changes TEXT,
	charging_rule_id INTEGER,
	eir_id INTEGER,
	emergency_subscriber_id INTEGER,
	id INTEGER NOT NULL,
	ims_subscriber_id INTEGER,
	imsi_imei_history_id INTEGER,
	item_id INTEGER NOT NULL,
	last_modified VARCHAR(100),
	operation VARCHAR(10),
	operation_id VARCHAR(36) NOT NULL,
	roaming_network_id INTEGER,
	roaming_rule_id INTEGER,
	serving_apn_id INTEGER,
	subscriber_attributes_id INTEGER,
	subscriber_id INTEGER,
	subscriber_routing_id INTEGER,
	table_name VARCHAR(255),
	tft_id INTEGER,
	timestamp DATETIME,
	PRIMARY KEY (id),
	FOREIGN KEY(apn_id) REFERENCES apn (apn_id),
	FOREIGN KEY(subscriber_routing_id) REFERENCES subscriber_routing (subscriber_routing_id),
	FOREIGN KEY(serving_apn_id) REFERENCES serving_apn (serving_apn_id),
	FOREIGN KEY(auc_id) REFERENCES auc (auc_id),
	FOREIGN KEY(subscriber_id) REFERENCES subscriber (subscriber_id),
	FOREIGN KEY(ims_subscriber_id) REFERENCES ims_subscriber (ims_subscriber_id),
	FOREIGN KEY(roaming_rule_id) REFERENCES roaming_rule (roaming_rule_id),
	FOREIGN KEY(roaming_network_id) REFERENCES roaming_network (roaming_network_id),
	FOREIGN KEY(emergency_subscriber_id) REFERENCES emergency_subscriber (emergency_subscriber_id),
	FOREIGN KEY(charging_rule_id) REFERENCES charging_rule (charging_rule_id),
	FOREIGN KEY(tft_id) REFERENCES tft (tft_id),
	FOREIGN KEY(eir_id) REFERENCES eir (eir_id),
	FOREIGN KEY(imsi_imei_history_id) REFERENCES eir_history (imsi_imei_history_id),
	FOREIGN KEY(subscriber_attributes_id) REFERENCES subscriber_attributes (subscriber_attributes_id)
);
CREATE TABLE roaming_network (
	last_modified VARCHAR(100),
	mcc VARCHAR(100),
	mnc VARCHAR(100),
	name VARCHAR(512),
	preference INTEGER,
	roaming_network_id INTEGER NOT NULL,
	PRIMARY KEY (roaming_network_id)
);
CREATE TABLE roaming_rule (
	allow BOOLEAN,
	enabled BOOLEAN,
	last_modified VARCHAR(100),
	roaming_network_id INTEGER,
	roaming_rule_id INTEGER NOT NULL,
	PRIMARY KEY (roaming_rule_id),
	FOREIGN KEY(roaming_network_id) REFERENCES roaming_network (roaming_network_id) ON DELETE CASCADE
);
CREATE TABLE serving_apn (
	apn INTEGER,
	ip_version INTEGER,
	last_modified VARCHAR(100),
	pcrf_session_id VARCHAR(100),
	serving_apn_id INTEGER NOT NULL,
	serving_pgw VARCHAR(512),
	serving_pgw_peer VARCHAR(512),
	serving_pgw_realm VARCHAR(512),
	serving_pgw_timestamp DATETIME,
	subscriber_id INTEGER,
	subscriber_routing VARCHAR(100),
	PRIMARY KEY (serving_apn_id),
	FOREIGN KEY(subscriber_id) REFERENCES subscriber (subscriber_id) ON DELETE CASCADE,
	FOREIGN KEY(apn) REFERENCES apn (apn_id) ON DELETE CASCADE
);
CREATE TABLE subscriber (
	apn_list VARCHAR(64) NOT NULL,
	auc_id INTEGER NOT NULL,
	default_apn INTEGER NOT NULL,
	enabled BOOLEAN,
	imsi VARCHAR(18),
	last_location_update_timestamp DATETIME,
	last_modified VARCHAR(100),
	last_seen_cell_id VARCHAR(64),
	last_seen_eci VARCHAR(64),
	last_seen_enodeb_id VARCHAR(64),
	last_seen_mcc VARCHAR(3),
	last_seen_mnc VARCHAR(3),
	last_seen_tac VARCHAR(64),
	msisdn VARCHAR(18),
	nam INTEGER,
	roaming_enabled BOOLEAN,
	roaming_rule_list VARCHAR(512),
	serving_mme VARCHAR(512),
	serving_mme_peer VARCHAR(512),
	serving_mme_realm VARCHAR(512),
	serving_mme_timestamp DATETIME,
	serving_msc VARCHAR(512),
	serving_msc_timestamp DATETIME,
	serving_sgsn VARCHAR(512),
	serving_sgsn_timestamp DATETIME,
	serving_vlr VARCHAR(512),
	serving_vlr_timestamp DATETIME,
	subscribed_rau_tau_timer INTEGER,
	subscriber_id INTEGER NOT NULL,
	ue_ambr_dl INTEGER,
	ue_ambr_ul INTEGER,
	PRIMARY KEY (subscriber_id),
	UNIQUE (imsi),
	FOREIGN KEY(auc_id) REFERENCES auc (auc_id),
	FOREIGN KEY(default_apn) REFERENCES apn (apn_id)
);
CREATE TABLE subscriber_attributes (
	"key" VARCHAR(60),
	last_modified VARCHAR(100),
	subscriber_attributes_id INTEGER NOT NULL,
	subscriber_id INTEGER NOT NULL,
	value VARCHAR(12000),
	PRIMARY KEY (subscriber_attributes_id),
	FOREIGN KEY(subscriber_id) REFERENCES subscriber (subscriber_id) ON DELETE CASCADE
);
CREATE TABLE subscriber_routing (
	apn_id INTEGER,
	ip_address VARCHAR(254),
	ip_version INTEGER,
	last_modified VARCHAR(100),
	subscriber_id INTEGER,
	subscriber_routing_id INTEGER NOT NULL,
	PRIMARY KEY (subscriber_routing_id),
	UNIQUE (subscriber_id, apn_id),
	FOREIGN KEY(subscriber_id) REFERENCES subscriber (subscriber_id) ON DELETE CASCADE,
	FOREIGN KEY(apn_id) REFERENCES apn (apn_id) ON DELETE CASCADE
);
CREATE TABLE tft (
	direction INTEGER NOT NULL,
	last_modified VARCHAR(100),
	tft_group_id INTEGER NOT NULL,
	tft_id INTEGER NOT NULL,
	tft_string VARCHAR(100) NOT NULL,
	PRIMARY KEY (tft_id)
);
COMMIT;
