"""Service Overhaul revision

Revision ID: 2ad87e0c0c76
Revises: 
Create Date: 2023-09-29 04:28:33.635508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad87e0c0c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_subscriber', sa.Column('pcscf', sa.String(length=512), nullable=True))
    op.add_column('ims_subscriber', sa.Column('pcscf_realm', sa.String(length=512), nullable=True))
    op.add_column('ims_subscriber', sa.Column('pcscf_timestamp', sa.DateTime(), nullable=True))
    op.add_column('ims_subscriber', sa.Column('pcscf_peer', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ims_subscriber', 'pcscf_peer')
    op.drop_column('ims_subscriber', 'pcscf_timestamp')
    op.drop_column('ims_subscriber', 'pcscf_realm')
    op.drop_column('ims_subscriber', 'pcscf')
    # ### end Alembic commands ###
