"""Added missing fields to DB

Revision ID: 851e500507f5
Revises: ff009e89c052
Create Date: 2025-08-18 19:38:58.677054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851e500507f5'
down_revision = 'ff009e89c052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('last_seen_eci', sa.String(length=64), nullable=True))
    op.add_column('subscriber', sa.Column('last_seen_enodeb_id', sa.String(length=64), nullable=True))
    op.add_column('subscriber', sa.Column('last_seen_cell_id', sa.String(length=64), nullable=True))
    op.add_column('subscriber', sa.Column('last_seen_tac', sa.String(length=64), nullable=True))
    op.add_column('subscriber', sa.Column('last_seen_mcc', sa.String(length=3), nullable=True))
    op.add_column('subscriber', sa.Column('last_seen_mnc', sa.String(length=3), nullable=True))
    op.add_column('subscriber', sa.Column('last_location_update_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'last_location_update_timestamp')
    op.drop_column('subscriber', 'last_seen_mnc')
    op.drop_column('subscriber', 'last_seen_mcc')
    op.drop_column('subscriber', 'last_seen_tac')
    op.drop_column('subscriber', 'last_seen_cell_id')
    op.drop_column('subscriber', 'last_seen_enodeb_id')
    op.drop_column('subscriber', 'last_seen_eci')
    # ### end Alembic commands ###
