"""Added 2G Support

Revision ID: a3d67d28ee08
Revises: 
Create Date: 2025-05-10 08:40:54.668117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d67d28ee08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auc', sa.Column('algo', sa.String(length=20), nullable=True))
    op.add_column('subscriber', sa.Column('serving_msc', sa.String(length=512), nullable=True))
    op.add_column('subscriber', sa.Column('serving_msc_timestamp', sa.DateTime(), nullable=True))
    op.add_column('subscriber', sa.Column('serving_sgsn', sa.String(length=512), nullable=True))
    op.add_column('subscriber', sa.Column('serving_sgsn_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'serving_sgsn_timestamp')
    op.drop_column('subscriber', 'serving_sgsn')
    op.drop_column('subscriber', 'serving_msc_timestamp')
    op.drop_column('subscriber', 'serving_msc')
    op.drop_column('auc', 'algo')
    # ### end Alembic commands ###
