"""Added VLR Column

Revision ID: ff009e89c052
Revises: a3d67d28ee08
Create Date: 2025-05-10 09:38:15.384529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff009e89c052'
down_revision = 'a3d67d28ee08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('serving_vlr', sa.String(length=512), nullable=True))
    op.add_column('subscriber', sa.Column('serving_vlr_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'serving_vlr_timestamp')
    op.drop_column('subscriber', 'serving_vlr')
    # ### end Alembic commands ###
