{
 "title": "PyHSS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Diameter Requests Per Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(prom_diam_request_count_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diameter Requests Per Vendor ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(diameter_application_id) (rate(prom_diam_request_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time by Diameter Application",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(diameter_application_id) (histogram_quantile(0.95, rate(prom_diam_response_time_method_bucket[5m])))"
      }
     ]
    },
    {
     "title": "Diameter Avg Response Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(prom_diam_response_time_diam_bucket[1h])))"
      }
     ]
    },
    {
     "title": "Diameter Avg Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(prom_diam_response_time_diam_bucket[10m])))"
      }
     ]
    },
    {
     "title": "Response Time per Peer",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(endpoint) (histogram_quantile(0.95, rate(prom_diam_response_time_method_bucket[15m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Diameter Command Codes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(diameter_cmd_code) (rate(prom_diam_request_count_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diameter Requests Per Command Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(diameter_cmd_code) (rate(prom_diam_request_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Diameter Requests Peer Peer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(prom_diam_request_count_total[30m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(prom_diam_request_count_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diameter Peer State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(endpoint) (prom_diam_connected_peers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Diameter Peers",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Diameter Peers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prom_diam_connected_peers)", "legendFormat": "__auto" }
   ]
  }
 ]
}